apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # image: nginx:1.14.2
        image: 770255773224.dkr.ecr.eu-central-1.amazonaws.com/test-clouddrove-ecr:ngnix
        ports:
        - containerPort: 80

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ngnix
# spec:
#   ports:
#     - port: 80
#       name: port80
#   selector:
#     app: nginx

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
   - port: 80
     name: nginx80
   - port: 443
     name: nginx443

  selector:
    app: nginx
  type: LoadBalancer
